spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=gold
    username: zlpostgres
    password: UEdqe8xZxm8Ga8z
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  enabled: true